export const V2_ROUTE_REGISTRY = [
  {
    key: 'validation',
    title: 'Validação V2',
    productionPath: '—',
    v2Path: '/v2/validacao',
    permission: 'team.view',
    domain: 'Governança',
    risk: 'Baixo',
    stage: 'Ferramenta de validação',
    promotion: 'Não promove tela produtiva',
    checks: ['Endpoints GET respondendo', 'Comparativo produção x V2', 'Sem escrita no banco'],
  },
  {
    key: 'dashboard',
    title: 'Dashboard',
    productionPath: '/',
    v2Path: '/v2/dashboard',
    permission: 'central.view',
    domain: 'Operação',
    risk: 'Alto',
    stage: 'Comparação obrigatória',
    promotion: 'Promover só após indicadores baterem por mês e squad',
    checks: ['MRR', 'Churn', 'Retenção', 'Metas', 'Ranking refletido sem recalcular no front'],
  },
  {
    key: 'clients',
    title: 'Clientes',
    productionPath: '/clientes',
    v2Path: '/v2/clientes',
    permission: 'clients.view',
    domain: 'Clientes',
    risk: 'Médio',
    stage: 'Apto para validação visual',
    promotion: 'Promover antes das telas críticas se status e leitura baterem',
    checks: ['Status ativo', 'Churn separado', 'Finalizado separado', 'MRR exibido', 'Busca e filtros'],
  },
  {
    key: 'weekly',
    title: 'Preencher Semana',
    productionPath: '/preencher-semana',
    v2Path: '/v2/preencher-semana',
    permission: 'metrics.view',
    domain: 'Métricas semanais',
    risk: 'Crítico',
    stage: 'Somente leitura',
    promotion: 'Não promover até existir espelho de edição validado em staging',
    checks: ['Sem POST/PUT', 'Dados semanais reais', 'Bate com Squad', 'Bate com Ranking'],
  },
  {
    key: 'squads',
    title: 'Squads',
    productionPath: '/squads/:squadId',
    v2Path: '/v2/squads',
    permission: 'squads.view',
    domain: 'Carteira',
    risk: 'Crítico',
    stage: 'Somente leitura',
    promotion: 'Promover apenas depois de Preencher Semana e Ranking estarem consistentes',
    checks: ['Carteira ativa', 'Onboarding', 'Rampagem', 'Meta lucro', 'MRR por squad'],
  },
  {
    key: 'rankings',
    title: 'Rankings',
    productionPath: '/ranking-squads',
    v2Path: '/v2/rankings',
    permission: 'ranking.view',
    domain: 'Ranking',
    risk: 'Alto',
    stage: 'Comparação obrigatória',
    promotion: 'Promover só depois de confirmar campeão fechado e ranking ao vivo separados',
    checks: ['Ranking ao vivo', 'Campeões fechados', 'Sem exibir mês aberto', 'GDVs preservados'],
  },
  {
    key: 'gdvs',
    title: 'GDVs',
    productionPath: '/ranking-gdvs',
    v2Path: '/v2/gdvs',
    permission: 'ranking.view',
    domain: 'GDV',
    risk: 'Alto',
    stage: 'Comparação obrigatória',
    promotion: 'Promover junto com Rankings se números baterem',
    checks: ['Ranking por GDV', 'Contratos previstos', 'Conversão', 'Base de clientes'],
  },
  {
    key: 'retention',
    title: 'Retenção',
    productionPath: '/dashboard/indicadores-por-squad',
    v2Path: '/v2/retencao',
    permission: 'central.view',
    domain: 'Retenção',
    risk: 'Alto',
    stage: 'Comparação obrigatória',
    promotion: 'Promover só após churn/finalizado baterem com histórico',
    checks: ['Churn da carteira', 'Churn precoce', 'LTV', 'Distribuição', 'Finalizado fora de churn'],
  },
  {
    key: 'traffic',
    title: 'Gestão de Tráfego',
    productionPath: '/gestao-trafego',
    v2Path: '/v2/gestao-trafego',
    permission: 'metrics.view',
    domain: 'Tráfego',
    risk: 'Médio',
    stage: 'Apto para validação visual',
    promotion: 'Promover depois de confirmar que não cria lançamento novo',
    checks: ['Gestor selecionado', 'Dados semanais existentes', 'CPL alto', 'Projeção ruim', 'ICP fora da meta'],
  },
  {
    key: 'model',
    title: 'Modelo Oficial',
    productionPath: '/modelo-oficial',
    v2Path: '/v2/modelo-oficial',
    permission: 'project_template.view',
    domain: 'Modelo',
    risk: 'Baixo',
    stage: 'Apto para promoção controlada',
    promotion: 'Pode ser uma das primeiras promoções se leitura bater',
    checks: ['GET /api/template', 'Sem salvar', 'Sem resetar', 'Estrutura preservada'],
  },
  {
    key: 'team',
    title: 'Equipe',
    productionPath: '/equipe',
    v2Path: '/v2/equipe',
    permission: 'team.view',
    domain: 'Admin',
    risk: 'Médio',
    stage: 'Somente leitura',
    promotion: 'Promover só depois de criar fluxo de edição com confirmação',
    checks: ['Usuários', 'Permissões', 'Squads', 'GDVs', 'Sem editar acesso'],
  },
  {
    key: 'projects',
    title: 'Projetos',
    productionPath: '/projetos',
    v2Path: '/v2/projetos',
    permission: 'projects.view',
    domain: 'Projetos',
    risk: 'Médio',
    stage: 'Somente leitura',
    promotion: 'Validar vínculos com clientes antes de promover',
    checks: ['Projetos', 'Demandas', 'Responsáveis', 'Sem alterar tarefas'],
  },
  {
    key: 'profile',
    title: 'Perfil',
    productionPath: '/perfil',
    v2Path: '/v2/perfil',
    permission: 'profile.view',
    domain: 'Perfil',
    risk: 'Baixo',
    stage: 'Apto para validação visual',
    promotion: 'Promover depois de conferir permissões e demandas pessoais',
    checks: ['Usuário atual', 'Permissões', 'Squads vinculados', 'Demandas'],
  },
  {
    key: 'workspace',
    title: 'Workspace',
    productionPath: '/espaco-trabalho',
    v2Path: '/v2/workspace',
    permission: 'profile.view',
    domain: 'Workspace',
    risk: 'Médio',
    stage: 'Somente leitura',
    promotion: 'Não promover até reconstruir edição de planilhas/documentos',
    checks: ['Documentos', 'Planilhas', 'Linhas recentes', 'Sem alterar conteúdo'],
  },
  {
    key: 'support',
    title: 'Suporte TI',
    productionPath: '/suporte-tecnologia',
    v2Path: '/v2/suporte-tecnologia',
    permission: 'support.view',
    domain: 'Suporte',
    risk: 'Médio',
    stage: 'Somente leitura',
    promotion: 'Manter oculta enquanto Suporte TI não voltar para sidebar',
    checks: ['Demandas', 'Rotina diária', 'Responsável', 'Sem edição'],
  },
];

export const V2_PROMOTION_BLOCKERS = [
  'Não promover tela que ainda depende de escrita se a V2 estiver somente leitura.',
  'Não promover Ranking, Squad ou Preencher Semana sem comparação numérica no mesmo mês, squad e cliente.',
  'Não promover Dashboard se qualquer indicador for recalculado no frontend de forma diferente do backend.',
  'Não remover rota ou componente legado no mesmo deploy em que uma V2 for promovida.',
  'Não rodar migration junto com promoção de rota V2.',
  'Manter rota legacy temporária para rollback durante pelo menos um ciclo de validação.',
];

export function routeMatrixRows() {
  return V2_ROUTE_REGISTRY
    .filter((route) => route.productionPath !== '—')
    .map((route) => [route.title, route.productionPath, route.v2Path, route.permission, route.checks[0] || route.promotion]);
}

export function promotionCandidates() {
  return V2_ROUTE_REGISTRY.filter((route) => ['Baixo', 'Médio'].includes(route.risk));
}

export function criticalRoutes() {
  return V2_ROUTE_REGISTRY.filter((route) => ['Alto', 'Crítico'].includes(route.risk));
}
