ALTER TABLE squads
  ADD COLUMN IF NOT EXISTS cover_position_x TINYINT UNSIGNED NOT NULL DEFAULT 50 AFTER cover_data_url,
  ADD COLUMN IF NOT EXISTS cover_position_y TINYINT UNSIGNED NOT NULL DEFAULT 50 AFTER cover_position_x,
  ADD COLUMN IF NOT EXISTS cover_zoom SMALLINT UNSIGNED NOT NULL DEFAULT 100 AFTER cover_position_y;
